//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedClassLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharedClassLibrary.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are Tasks associated with this task type, we cannot change the value type..
        /// </summary>
        public static string CannotChangeTaskValueType {
            get {
                return ResourceManager.GetString("CannotChangeTaskValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0}?.
        /// </summary>
        public static string DeleteItemConfirmation {
            get {
                return ResourceManager.GetString("DeleteItemConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi,&lt;br /&gt;&lt;br /&gt;
        ///Your password reset code is {0}, please use this code to reset your password.
        ///&lt;br&gt;
        ///Thanks, Middle Manager team.
        ///.
        /// </summary>
        public static string EmailVarificationMessage {
            get {
                return ResourceManager.GetString("EmailVarificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email verification code.
        /// </summary>
        public static string EmailVerificationCode {
            get {
                return ResourceManager.GetString("EmailVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been invited to use Middle Manager.
        /// </summary>
        public static string InvitedtoUseMiddleManager {
            get {
                return ResourceManager.GetString("InvitedtoUseMiddleManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi,&lt;br /&gt;&lt;br /&gt;
        ///Welcome to Middle Manager, you&apos;ve been invited by {0} to track your task progress. 
        ///Find us on the Apple app store at {1} or the Google play store at {2}.
        ///&lt;br&gt;
        ///Your username is &lt;b&gt; {3} &lt;/b&gt; &lt;br/&gt;
        ///Your temporary password: &lt;b&gt; {4} &lt;/b&gt;&lt;br/&gt;
        ///Please use these details to sign in. .
        /// </summary>
        public static string InviteEmailContent {
            get {
                return ResourceManager.GetString("InviteEmailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Middle Manager!.
        /// </summary>
        public static string InviteSubject {
            get {
                return ResourceManager.GetString("InviteSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {0}.
        /// </summary>
        public static string ItemDashItem {
            get {
                return ResourceManager.GetString("ItemDashItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle manager.
        /// </summary>
        public static string MiddleManager {
            get {
                return ResourceManager.GetString("MiddleManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset code.
        /// </summary>
        public static string PasswordResetCode {
            get {
                return ResourceManager.GetString("PasswordResetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - {0}.
        /// </summary>
        public static string PrependDashItem {
            get {
                return ResourceManager.GetString("PrependDashItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required task completion date.
        /// </summary>
        public static string RequiredTaskCompletionDate {
            get {
                return ResourceManager.GetString("RequiredTaskCompletionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Middle Manager!.
        /// </summary>
        public static string WelcomeToMiddleManager {
            get {
                return ResourceManager.GetString("WelcomeToMiddleManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
